name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-js-sample .
          docker save -o /tmp/docker-image.tar ${{ secrets.DOCKER_USERNAME }}/node-js-sample

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/docker-image.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/docker-image.tar

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name node-js-sample ${{ secrets.DOCKER_USERNAME }}/node-js-sample

      - name: Check if container is running
        run: docker ps -a

      - name: Check container logs
        run: docker logs node-js-sample || echo "No logs found"

      - name: Wait for the app to be ready
        run: sleep 5

      - name: Test application endpoint
        run: docker exec node-js-sample curl --fail http://localhost:8080/ || (docker logs node-js-sample && exit 1)

      - name: Stop and remove container
        run: docker stop node-js-sample && docker rm node-js-sample

  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-js-sample
