name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-js-sample:latest .

      - name: Persist workspace
        run: echo "Workspace persisted"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name node-js-sample ${{ secrets.DOCKER_USERNAME }}/node-js-sample:latest

      - name: Wait for the app to be ready
        run: sleep 5

      - name: Test application endpoint
        run: |
          docker exec node-js-sample curl --fail http://localhost:8080/ || (docker logs node-js-sample && exit 1)

      - name: Stop and remove container
        run: docker stop node-js-sample && docker rm node-js-sample

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-js-sample:latest

workflows:
  version: 2
  build-test-push:
    jobs:
      - build
      - test:
          needs: build
      - push:
          needs: test
